function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 21-Sep-2024
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Create empty mask
BW = false(size(X,1),size(X,2));

% Local graph cut
xPos = [425.0736 459.8509 459.8509 425.0736 ];
yPos = [179.7000 179.7000 206.7491 206.7491 ];
m = size(BW, 1);
n = size(BW, 2);
ROI = poly2mask(xPos,yPos,m,n);
foregroundInd = [220864 221377 221378 221890 221891 222403 222914 222915 223424 223425 223426 227007 227008 227520 228033 228034 228035 228547 229059 229566 229571 230078 230081 230082 230083 230590 230591 230592 230593 ];
backgroundInd = [];
L = superpixels(X,1411);
BW = BW | grabcut(X,L,ROI,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

